export const APP_LOAD = 'APP_LOAD';
export const REDIRECT = 'REDIRECT';
export const ASYNC_START = 'ASYNC_START';
export const ASYNC_END = 'ASYNC_END';
export const GOTO = 'GOTO';

export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const UPDATE_FIELD_AUTH = 'UPDATE_FIELD_AUTH';
export const LOGIN_PAGE_UNLOADED = 'LOGIN_PAGE_UNLOADED';

export const REGISTER = 'REGISTER';
export const REGISTER_PAGE_UNLOADED = 'REGISTER_PAGE_UNLOADED';

export const SETTINGS_SAVED = 'SETTINGS_SAVED';
export const SETTINGS_PAGE_UNLOADED = 'SETTINGS_PAGE_UNLOADED';

export const PROFILE_PAGE_LOADED = 'PROFILE_PAGE_LOADED';
export const DELETE_PATIENT = 'DELETE_PATIENT';
export const DELETE_THERAPIST = 'DELETE_THERAPIST';
export const PROFILE_PAGE_UNLOADED = 'PROFILE_PAGE_UNLOADED';

export const PATIENT_EDITOR_PAGE_LOADED = 'PATIENT_EDITOR_PAGE_LOADED';
export const PATIENT_SUBMITTED = 'PATIENT_SUBMITTED';
export const UPDATE_FIELD_PATIENT_EDITOR = 'UPDATE_FIELD_PATIENT_EDITOR';
export const PATIENT_EDITOR_PAGE_UNLOADED = 'PATIENT_EDITOR_PAGE_UNLOADED';
export const PATIENT_ADDED = 'PATIENT_ADDED';
export const PATIENT_UPDATED = 'PATIENT_UPDATED';
export const PATIENT_EDITOR_PAGE_TOGGLED = 'PATIENT_EDITOR_PAGE_TOGGLED';

export const THERAPIST_EDITOR_PAGE_LOADED = 'THERAPIST_EDITOR_PAGE_LOADED';
export const THERAPIST_SUBMITTED = 'THERAPIST_SUBMITTED';
export const UPDATE_FIELD_THERAPIST_EDITOR = 'UPDATE_FIELD_THERAPIST_EDITOR';
export const THERAPIST_EDITOR_PAGE_UNLOADED = 'THERAPIST_EDITOR_PAGE_UNLOADED';
export const THERAPIST_ADDED = 'THERAPIST_ADDED';
export const THERAPIST_UPDATED = 'THERAPIST_UPDATED';
export const THERAPIST_EDITOR_PAGE_TOGGLED = 'THERAPIST_EDITOR_PAGE_TOGGLED';

export const HOME_PAGE_LOADED = 'HOME_PAGE_LOADED';
export const SET_PAGE = 'SET_PAGE';
export const HOME_PAGE_UNLOADED = 'HOME_PAGE_UNLOADED';

export const EDITOR_PAGE_LOADED = 'EDITOR_PAGE_LOADED';
export const EDITOR_PAGE_UNLOADED = 'EDITOR_PAGE_UNLOADED';

export const REPORT_SUBMITTED = 'REPORT_SUBMITTED';
export const DELETE_REPORT = 'DELETE_REPORT';
export const UPDATE_FIELD_REPORT = 'UPDATE_FIELD_REPORT';

export const REPORT_PDF_CREATED = 'REPORT_PDF_CREATED';
export const REPORT_DOWNLOADED = 'REPORT_DOWNLOADED';
export const REPORT_UPLOADED = 'REPORT_UPLOADED';
export const EDITOR_SIDENAV_LOADED = 'EDITOR_SIDENAV_LOADED';
export const EDITOR_SIDENAV_UNLOADED = 'EDITOR_SIDENAV_UNLOADED';

export const FUNCTION_SUBMITTED = 'FUNCTION_SUBMITTED';
export const DELETE_FUNCTION = 'DELETE_FUNCTION';
export const FUNCTION_ADDED = 'FUNCTION_ADDED';
export const UPDATE_FIELD_FUNCTION = 'UPDATE_FIELD_FUNCTION';
export const UPDATE_FIELD_FUNCTION_VALUE = 'UPDATE_FIELD_FUNCTION_VALUE';
export const DELETE_STRUCTURE = 'DELETE_STRUCTURE';
export const STRUCTURE_ADDED = 'STRUCTURE_ADDED';
export const UPDATE_FIELD_STRUCTURE = 'UPDATE_FIELD_STRUCTURE';
export const UPDATE_FIELD_STRUCTURE_VALUE = 'UPDATE_FIELD_STRUCTURE_VALUE';
export const DELETE_ACTIVITY = 'DELETE_ACTIVITY';
export const ACTIVITY_ADDED = 'ACTIVITY_ADDED';
export const UPDATE_FIELD_ACTIVITY = 'UPDATE_FIELD_ACTIVITY';
export const UPDATE_FIELD_ACTIVITY_VALUE = 'UPDATE_FIELD_ACTIVITY_VALUE';
export const DELETE_CONTEXT = 'DELETE_CONTEXT';
export const CONTEXT_ADDED = 'CONTEXT_ADDED';
export const UPDATE_FIELD_CONTEXT = 'UPDATE_FIELD_CONTEXT';
export const UPDATE_FIELD_CONTEXT_VALUE = 'UPDATE_FIELD_CONTEXT_VALUE';
export const FUNCTION_SAVED = 'FUNCTION_SAVED';

export const CODE_PAGE_LOADED = 'CODE_PAGE_LOADED';
export const CODE_PAGE_UNLOADED = 'CODE_PAGE_UNLOADED';
export const CODE_SUBMITTED = 'CODE_SUBMITTED';
export const DELETE_CODE = 'DELETE_CODE';
export const CODE_ADDED = 'CODE_ADDED';
export const CODE_UPDATED = 'CODE_UPDATED';
export const CODE_SELECTED = 'CODE_SELECTED';
export const CODE_CLEARED = 'CODE_CLEARED';
export const UPDATE_FIELD_CODE = 'UPDATE_FIELD_CODE';